packages:
  - "apps/*"
  - "packages/*"
  - "packages/server/*"
overrides:
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  mermaid: ^11.14.1
  postcss: ^8.5.10
allowBuilds:
  cpu-features: false
  sharp: true
  ssh2: false
  unrs-resolver: true
