import type { WrappedSlideData } from "../types";

/**
 * Placeholder DSC Wrapped slides.
 *
 * TODO(db): Replace this static array with data fetched per-user. The intended
 * path is a `lib/api/` client wrapper -> `app/api/wrapped` route -> service ->
 * repository (see CLAUDE.md "API architecture"). Components consume
 * `WrappedSlideData[]`, so swapping the source here is the only change needed.
 */
export const WRAPPED_SLIDES: readonly WrappedSlideData[] = [
  {
    id: "intro",
    layout: "hero",
    eyebrow: "Data Science Club",
    title: "Your DSC Wrapped",
    subtitle: "Let's look back at everything since you joined.",
    background: "bg-gradient-to-br from-indigo-600 via-purple-600 to-fuchsia-600",
    foreground: "text-white",
  },
  {
    id: "events-nutshell",
    layout: "events-nutshell",
    heading: "YOUR EVENTS IN A NUTSHELL",
    events: [
      {
        id: "event-1",
        name: "Event Name",
        description: "Event description",
        color: "#9cd8ea",
      },
      {
        id: "event-2",
        name: "Event Name",
        description: "Event description",
        color: "#ff8f64",
      },
      {
        id: "event-3",
        name: "Event Name",
        description: "Event description",
        color: "#ff7075",
      },
      {
        id: "event-4",
        name: "Event Name",
        description: "Event description",
        color: "#ccda96",
      },
      {
        id: "event-5",
        name: "Event Name",
        description: "Event description",
        color: "#e6c6e0",
      },
    ],
    statValue: "5",
    statCaption: "total events attended with us!",
  },
  {
    id: "streak",
    layout: "streak",
    heading: "YOUR LONGEST STREAK",
    visual: { color: "#ff8f64" },
    subheading: "YOU'RE ON FIRE!!!",
    captionLines: ["That's more than 65%", "of other members of DSC"],
  },
  {
    id: "membership",
    layout: "membership",
    eyebrow: "Your first day w DSC",
    joinDate: "January 10, 2024",
    visual: { color: "#e6c6e0" },
    headline: "# terms since then as a member!",
    caption: "# number of days with us!",
  },
  {
    id: "minutes",
    layout: "hero",
    eyebrow: "Locked in",
    title: "Minutes on the site",
    stat: "0",
    subtitle: "Browsing events, your profile, and more.",
    background: "bg-gradient-to-br from-violet-600 via-indigo-600 to-blue-700",
    foreground: "text-white",
  },
  {
    id: "password-resets",
    layout: "hero",
    eyebrow: "Oops",
    title: "Password resets",
    stat: "0",
    subtitle: "We've all been there.",
    background: "bg-gradient-to-br from-slate-600 via-gray-700 to-zinc-800",
    foreground: "text-white",
  },
  {
    id: "top-event",
    layout: "hero",
    eyebrow: "Your headliner",
    title: "Top event",
    subtitle: "Placeholder Event Name",
    background: "bg-gradient-to-br from-amber-400 via-orange-500 to-rose-500",
    foreground: "text-white",
  },
  {
    id: "club-highest-attendance",
    layout: "hero",
    eyebrow: "Club fun fact",
    title: "Highest-attendance event",
    stat: "0",
    subtitle: "Placeholder Event Name packed the room.",
    background: "bg-gradient-to-br from-fuchsia-500 via-purple-600 to-indigo-700",
    foreground: "text-white",
  },
  {
    id: "club-most-visited",
    layout: "hero",
    eyebrow: "Club fun fact",
    title: "Most visited event page",
    subtitle: "Placeholder Event Name had everyone clicking.",
    background: "bg-gradient-to-br from-cyan-500 via-sky-600 to-blue-700",
    foreground: "text-white",
  },
  {
    id: "club-snack",
    layout: "hero",
    eyebrow: "Club fun fact",
    title: "Most common snack",
    subtitle: "Placeholder Snack fueled the club this year.",
    background: "bg-gradient-to-br from-lime-500 via-green-600 to-emerald-700",
    foreground: "text-white",
  },
  {
    id: "award-chronically-online",
    layout: "hero",
    eyebrow: "Award unlocked",
    title: "Chronically Online 🏆",
    subtitle: "You spent a remarkable amount of time on the site.",
    background: "bg-gradient-to-br from-purple-600 via-violet-700 to-fuchsia-800",
    foreground: "text-white",
  },
  {
    id: "award-super-fan",
    layout: "hero",
    eyebrow: "Award unlocked",
    title: "DSC Super Fan 🌟",
    subtitle: "You showed up to more events than almost anyone.",
    background: "bg-gradient-to-br from-orange-500 via-amber-600 to-yellow-600",
    foreground: "text-white",
  },
  {
    id: "outro",
    layout: "hero",
    eyebrow: "That's a wrap",
    title: "Here's to what's next 👋",
    subtitle: "Thanks for being part of DSC since day one.",
    background: "bg-gradient-to-br from-emerald-500 via-teal-600 to-cyan-700",
    foreground: "text-white",
  },
];
